autoqc:
  pickup-dir: ''
  data-dir: '${svc.home}/data'
  concurrency: ${available.processors}
  test:
    aoml-climatology:
      net-cdf-url: 'https://auto-qc-data.s3.us-west-2.amazonaws.com/woa13_00_025.nc'
      net-cdf-file-name: 'woa13_00_025.nc'
      enabled: true
    aoml-gradient:
      enabled: true
    aoml-gross:
      enabled: true
    aoml-spike:
      enabled: true
    argo-impossible-date:
      enabled: true
    argo-impossible-location:
      enabled: true
    argo-regional-range:
      enabled: true
    en-bg-avail-check:
      enabled: true
      info-net-cdf-file-name: 'EN_bgcheck_info.nc'
      info-net-cdf-url: 'https://www.metoffice.gov.uk/hadobs/en4/data/EN_bgcheck_info.nc'
    icdc-aqc-09-local-climatology-check:
      enabled: true
      net-cdf-file-name: 'climatological_t_median_and_amd_for_aqc.nc'
      net-cdf-url: 'https://s3-us-west-2.amazonaws.com/autoqc/climatological_t_median_and_amd_for_aqc.nc'
    icdc-aqc-10-local-climatology-check:
      enabled: true
      net-cdf-file-name: 'climatological_t_median_and_amd_for_aqc.nc'
      net-cdf-url: 'https://s3-us-west-2.amazonaws.com/autoqc/climatological_t_median_and_amd_for_aqc.nc'

camel:
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

spring:
  main:
    web-application-type: none
